### ISSUE TITLE
Compile error: open() flag format mismatch?

### ISSUE THREAD

**Issue by v-p-b** [stef/klutshnik#1]
My compiler doesn't like this line:

https://github.com/stef/klutshnik/blob/master/noise.c#L233

```
noise.c:233:12: error: implicit declaration of function ‘open’; did you mean ‘popen’? [-Werror=implicit-function-declaration]
  233 |   int fd = open(path,'r');
```

I think this is a result if mixed up use of the `open()` and `fopen()` calls: the character 'r' has some bits set that makes fcntl2's `open()` implementation assume that the file is going to be created so it expects a third parameter for umask. 

I think the second parameter here should be `O_RDONLY` or `fopen()` should be used.

**Comment by stef** [comment]
but weird why my compiler doesn't complain about the missing declaration, i am running this with -Wall

**Comment by stef** [comment]
mmm, but i do include `#include <fcntl.h>` which cointains `open(2)` so why does your compiler complain?

**Comment by stef** [comment]
ah, you even gave a reason:
> the character 'r' has some bits set that makes fcntl2's open() implementation assume that the file is going to be created so it expects a third parameter for umask.

to early to read stuff yet... grabing some coffee

**Comment by v-p-b** [comment]
OK this is weird, after I merged your fix, this other one popped up:

https://github.com/stef/klutshnik/blob/master/server.c#L83

Same cause, and here O_CREAT is explicitly provided. It seems our fcntl's work differently? I'm on Debian 11, here is my gcc version:
```
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by stef** [comment]
hrmpf. i fucked it up again...

**Comment by stef** [comment]
does this fix this problem? https://github.com/stef/klutshnik/commit/c7a5417df1eda124a8e1ce4df95847e7560965e0 if so please close this issue!
