### ISSUE TITLE
Question about file key

### ISSUE THREAD

**Issue by stsch9** [stef/klutshnik#7]
Hi,
I really like this project.

One question: 
Normally you calculate the file key for symmetric encryption e.g. with `Hash(shared_key || publickey_A || publickey_B)` or you use `HKDF()` instead of `Hash()`. 
You only use `Hash(shared_key)` here (https://github.com/stef/klutshnik/blob/master/common.c#L45), because `publickey_A` and `publickey_B` change during a key rotation and you would get a different file key for the symmetric encryption. 
Would it make sense to choose a fixed nonce for each file and calculate the file key with `Hash(shared_key || nonce)` or `HDKF(ikm = shared_key, salt = nonce, info = "info")` to get a bit more "randomness"? 
(Similar to how the payload key is calculated in age https://github.com/C2SP/C2SP/blob/main/age.md#payload)

**Comment by stef** [comment]
actually that is not necessary, since each file has its own unique w value, see also here: https://github.com/stef/klutshnik?tab=readme-ov-file#file-formats - this unique w value is the input to the OPRF and thus also makes the DEK completely unique, and thus no need for "a bit more randomness".

**Comment by stef** [comment]
> I really like this project.
thanks!
:) me too

**Comment by stsch9** [comment]
Thank you for the explanation :-).
